#kubernetes/manifests/litellm-service.yaml
apiVersion: v1  # Core API 버전
kind: Service  # 서비스 리소스
metadata:
  name: litellm  # 서비스 이름 (kubectl, 다른 파드에서 접근할 때 사용)
spec:
  selector:
    app: litellm  # 이 라벨을 가진 파드에 트래픽 전달
  ports:
  - port: 4000  # 클러스터 내부에서 서비스가 노출하는 포트
    targetPort: 4000  # 실제 파드(컨테이너) 내부에서 열려 있는 포트
  type: ClusterIP  # 클러스터 내부에서만 접근 가능한 서비스 타입
