apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exporter
  namespace: default
  labels:
    app: nginx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
        - -nginx.scrape-uri=http://nginx-ab-proxy/nginx_status
        ports:
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: default
  labels:
    app: nginx-exporter
spec:
  ports:
  - port: 9113
    targetPort: 9113
    protocol: TCP
  selector:
    app: nginx-exporter