#kubernetes/manifests/openwebui-v1-service.yaml
apiVersion: v1  # Kubernetes core API 그룹 (Service는 항상 v1)
kind: Service  # 리소스 종류: 클러스터 내부 또는 외부로 트래픽을 전달하는 서비스
metadata:
  name: openwebui-v1  # 서비스 이름 (DNS 이름으로도 사용됨: openwebui-v1.default.svc.cluster.local)
  namespace: default  # 서비스가 생성될 네임스페이스 (여기선 default)
spec:
  selector:
    app: openwebui-v1  # 이 라벨을 가진 파드에 트래픽을 전달함
  ports:
    - protocol: TCP  # 사용할 프로토콜 (기본은 TCP)
      port: 8080      # 서비스가 노출할 포트 (클러스터 내부에서 접근 시 사용)
      targetPort: 8080  # 실제 파드 내부 컨테이너 포트
