#kubernetes/manifests/prometheus-service.yaml
apiVersion: v1
kind: Service  # 내부 통신을 위한 서비스 정의
metadata:
  name: prometheus  # 서비스 이름
spec:
  selector:
    app: prometheus  # 이 라벨을 가진 파드로 트래픽 전달
  ports:
    - port: 9090  # 클러스터 내부에서 노출할 포트
      targetPort: 9090  # 실제 컨테이너가 열고 있는 포트
  type: ClusterIP  # 클러스터 내부에서만 접근 가능 (웹 브라우저로 보려면 port-forward 필요)
