#kubernetes/manifests/prometheus.yaml
apiVersion: v1
kind: ConfigMap  # 설정 데이터를 key-value 형식으로 저장
metadata:
  name: prometheus-config  # ConfigMap 이름
  labels:
    app: prometheus  # 관련 리소스끼리 묶기 위한 라벨
data:
  prometheus.yml: |  # Prometheus 설정 파일 내용
    global:
      scrape_interval: 15s  # 메트릭 수집 주기 (기본값)
      evaluation_interval: 15s  # 규칙 평가 주기 (알람 등에서 사용)

    scrape_configs:
      - job_name: 'prometheus'  # 자체 Prometheus 서버 메트릭 수집
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'nginx'  # Nginx exporter를 수집 대상에 추가
        static_configs:
          - targets: ['nginx-exporter:9113']  # Nginx exporter 서비스의 주소

      # 향후 LiteLLM과 같은 LLM 서비스 모니터링 추가 가능
      # - job_name: 'litellm'
      #   static_configs:
      #     - targets: ['litellm:8000']
