#kubernetes/manifests/prometheus-deployment.yaml
apiVersion: apps/v1
kind: Deployment  # 파드 생명주기 및 배포 관리
metadata:
  name: prometheus  # Deployment 이름
  labels:
    app: prometheus
spec:
  replicas: 1  # 파드 1개만 실행 (단일 인스턴스 Prometheus)
  selector:
    matchLabels:
      app: prometheus  # 이 라벨을 가진 파드를 관리 대상으로 지정

  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus  # 컨테이너 이름
          image: prom/prometheus:latest  # 공식 Prometheus 이미지
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"  # 설정 파일 경로 지정
          ports:
            - containerPort: 9090  # Prometheus 웹 UI 포트
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus  # 설정 파일 마운트 위치
            - name: prometheus-data
              mountPath: /prometheus  # 메트릭 데이터를 저장할 위치

      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config  # 위 ConfigMap을 마운트
        - name: prometheus-data
          emptyDir: {}  # 임시 저장소 (파드가 삭제되면 데이터도 사라짐, 실운영에선 PVC 사용 권장)
